package GUI;

import Main.Admin;
import java.util.ArrayList;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.lang3.StringUtils;

public class ListPC extends javax.swing.JFrame {

    public GUI_clientad gui_clientad;
    public Admin admin;
    private String content = null;
    
    public ListPC() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        btnGo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPC = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnGo = new javax.swing.JButton();
        lbWarning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SYSTEM TRACKING PROGRAM");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbPC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No.", "PC NAME"
            }
        ));
        tbPC.setGridColor(new java.awt.Color(0, 0, 0));
        tbPC.setRowHeight(30);
        tbPC.setRowMargin(2);
        tbPC.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(tbPC);
        if (tbPC.getColumnModel().getColumnCount() > 0) {
            tbPC.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbPC.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LIST OF CURRENT CONNECTED PC");

        btnGo.setBackground(new java.awt.Color(51, 255, 255));
        btnGo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGo.setText("GO");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        lbWarning.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbWarning.setText("No user connected yet. Please wait!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(284, 284, 284)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(154, 154, 154)
                                    .addComponent(lbWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lbWarning)
                .addGap(14, 14, 14)
                .addComponent(btnGo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        // TODO add your handling code here:
        try{
            int selectedIndex=tbPC.getSelectedRow();
            String PCname = tbPC.getModel().getValueAt(selectedIndex,1).toString();

            gui_clientad.setLablePCName(PCname);
            gui_clientad.setVisible(true);
            admin.setReceiveForm(PCname);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please choose a PC.","Notify",0);
        }
            
        
        
    }//GEN-LAST:event_btnGoActionPerformed

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
    public void loadAll() {
        if(content!=null){
            lbWarning.setVisible(false);
            btnGo.setVisible(true);
            String[] header = { "No.","PC NAME"};
            DefaultTableModel dtm = new DefaultTableModel(header, 0);	 
            StringTokenizer st = new StringTokenizer(content,";");
            int i = 1 ;
            while (st.hasMoreTokens()) {
                String tmp = st.nextToken();
                String port = StringUtils.substringBetween(tmp, "port=", ",localport=");
                String name = "PC " + i + " [port: " + port + "]";
                Object[] row = { i,name};
                dtm.addRow(row);
                i++;
             }
            tbPC.setModel(dtm);
            tbPC.setGridColor(new java.awt.Color(0, 0, 0));
            tbPC.setFont(new java.awt.Font("Tahoma", 0, 16));
            tbPC.setRowHeight(30);
            tbPC.setRowMargin(2);
            tbPC.setSurrendersFocusOnKeystroke(true);
            jScrollPane1.setViewportView(tbPC);
            if (tbPC.getColumnModel().getColumnCount() > 0) {
                tbPC.getColumnModel().getColumn(0).setPreferredWidth(100);
                tbPC.getColumnModel().getColumn(1).setPreferredWidth(400);
            }
        }   
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbWarning;
    private javax.swing.JTable tbPC;
    // End of variables declaration//GEN-END:variables
}
